(()=>{const c=window.OAH_CONFIG,$=s=>document.querySelector(s);let csrf="";
const money=x=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((Number(x)||0)/100);
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const cls=x=>String(x||"").toLowerCase().replace(/[^a-z]/g,"");
let state={products:[],orders:[],stats:{},email:{},square:{}};
async function api(path,opt={}){const h={"Accept":"application/json",...(opt.body?{"Content-Type":"application/json"}:{}),...(opt.headers||{})};if(csrf)h["X-CSRF-Token"]=csrf;const r=await fetch(c.apiBaseUrl+path,{credentials:"include",...opt,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed.");return d}
function toast(s,ok=true){const e=$("#toast");e.textContent=s;e.className="toast show "+(ok?"ok":"error");clearTimeout(window.__t);window.__t=setTimeout(()=>e.className="toast",3000)}
function view(n){document.querySelectorAll(".admin-nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===n));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+n));$("#page-title").textContent=({dashboard:"Dashboard",products:"Products & Pricing",orders:"Orders",customers:"Customers",email:"Email Service",payments:"Payments",settings:"Settings"})[n]||"Dashboard"}
function render(){const s=state.stats||{};$("#stat-orders").textContent=s.orders||0;$("#stat-revenue").textContent=money(s.revenue_cents);$("#stat-paid").textContent=s.paid_count||0;$("#stat-messages").textContent=state.unread_messages||0;
$("#recent-orders").innerHTML=state.orders.slice(0,6).map(o=>'<div class="connection" style="margin-bottom:9px"><div><strong>'+esc(o.product_name)+'</strong><p class="muted">'+esc(o.customer_name)+' · '+esc(o.customer_email)+'</p></div><div style="text-align:right"><strong>'+money(o.amount_cents)+'</strong><br><span class="status '+cls(o.payment_status)+'">'+esc(o.payment_status)+'</span></div></div>').join("")||'<p class="muted">No orders yet.</p>';
$("#orders-table").innerHTML=state.orders.map(o=>'<tr><td><strong>'+esc(o.id)+'</strong><br><span class="muted">Square '+esc(o.square_payment_id||"pending")+'</span></td><td>'+esc(o.customer_name)+'<br><span class="muted">'+esc(o.customer_email)+'</span></td><td>'+esc(o.product_name)+'</td><td>'+money(o.amount_cents)+'</td><td><span class="status '+cls(o.payment_status)+'">'+esc(o.payment_status)+'</span></td><td>'+esc(new Date(o.created_at).toLocaleString())+'</td></tr>').join("")||'<tr><td colspan="6" class="muted">No orders yet.</td></tr>';
const cm=new Map();state.orders.forEach(o=>{let x=cm.get(o.customer_email)||{name:o.customer_name,email:o.customer_email,count:0,paid:0,last:o.created_at};x.count++;if(o.payment_status==="paid")x.paid+=Number(o.amount_cents||0);if(new Date(o.created_at)>new Date(x.last))x.last=o.created_at;cm.set(o.customer_email,x)});$("#customers-table").innerHTML=[...cm.values()].map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.email)+'</td><td>'+x.count+'</td><td>'+money(x.paid)+'</td><td>'+esc(new Date(x.last).toLocaleString())+'</td></tr>').join("")||'<tr><td colspan="5" class="muted">No customers yet.</td></tr>';
$("#products-list").innerHTML=state.products.map(p=>'<div class="product-row" data-product="'+esc(p.slug)+'"><div><b>'+esc(p.name)+'</b><div class="muted">'+esc(p.billing_type)+'</div></div><div class="field"><label>Price cents</label><input class="pp" type="number" min="0" value="'+p.price_cents+'"></div><div class="field"><label>Version</label><input class="pv" value="'+esc(p.version)+'"></div><div class="field"><label>Active</label><select class="pa"><option value="1" '+(p.active?"selected":"")+'>Live</option><option value="0" '+(!p.active?"selected":"")+'>Hidden</option></select></div><button class="btn primary save-product">SAVE</button></div>').join("");
document.querySelectorAll(".save-product").forEach(b=>b.onclick=async()=>{const r=b.closest(".product-row");try{await api(c.endpoints.adminProducts,{method:"PATCH",body:JSON.stringify({slug:r.dataset.product,price_cents:Number(r.querySelector(".pp").value),version:r.querySelector(".pv").value,active:r.querySelector(".pa").value==="1"})});toast("Product saved.");await load()}catch(e){toast(e.message,false)}});
$("#contact-to").value=state.email.contact_to||"";const es=!!state.email.contact_to;$("#email-status").className="status "+(es?"connected":"pending");$("#email-status").textContent=es?"Configured":"Needs setup";
const q=state.square||{},ok=q.connected&&q.configured&&q.locationConfigured;$("#square-status").className="status "+(ok?"connected":"pending");$("#square-status").textContent=ok?"Connected":"Needs setup";$("#square-environment").textContent=(q.environment||"—").toUpperCase();$("#square-detail").textContent=ok?"Worker can reach the configured Square location.":"Add the Square access token and location ID as Cloudflare Worker secrets/variables."}
async function load(){const d=await api(c.endpoints.adminOverview);state={...state,...d};try{state.square=await api(c.endpoints.adminSquareStatus)}catch{}render()}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),s=$("#login-status");s.textContent="Authenticating…";try{const d=await api(c.endpoints.adminLogin,{method:"POST",body:JSON.stringify({email:f.get("email"),password:f.get("password")})});csrf=d.csrf||"";$("#login-screen").hidden=true;$("#admin-shell").hidden=false;$("#admin-user").textContent=d.email+" · authenticated session";await load();toast("Secure session established.")}catch(x){s.textContent=x.message}}
async function boot(){try{const d=await api(c.endpoints.adminMe);if(d.ok){csrf=d.csrf||"";$("#login-screen").hidden=true;$("#admin-shell").hidden=false;$("#admin-user").textContent=d.email+" · authenticated session";await load()}}catch{}}
document.querySelectorAll(".admin-nav button").forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>view(b.dataset.jump));$("#login-form").onsubmit=login;$("#refresh").onclick=async()=>{try{await load();toast("Dashboard refreshed.")}catch(e){toast(e.message,false)}};$("#logout").onclick=async()=>{try{await api(c.endpoints.adminLogout,{method:"POST"})}finally{location.reload()}};$("#save-email").onclick=async()=>{try{await api(c.endpoints.adminEmailSettings,{method:"POST",body:JSON.stringify({contact_to:$("#contact-to").value})});toast("Email settings saved.");await load()}catch(e){toast(e.message,false)}};$("#test-email").onclick=async()=>{try{await api(c.endpoints.adminEmailTest,{method:"POST",body:"{}"});toast("Test email sent.")}catch(e){toast(e.message,false)}};boot()})();